CREATE TABLE "user" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email" text NOT NULL UNIQUE,
    "password" text NOT NULL,
    PRIMARY KEY ("id")

);

CREATE TABLE "role"
(
    "id"   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" text                                    NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "user_roles"
(
    "user_id" bigint NOT NULL,
    "role_id" bigint NOT NULL,
    UNIQUE (USER_ID, ROLE_ID)
);


CREATE TABLE "car" (
                       "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       "user_id" bigint NOT NULL,
                       "number" text NOT NULL,
                       PRIMARY KEY ("id")
);
CREATE TABLE "spot" (
                        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        "location" text NOT NULL,
                        PRIMARY KEY ("id")
);
CREATE TABLE "booking" (
                           "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           "car_id" bigint NOT NULL,
                           "spot_id" bigint NOT NULL,
                           "from" timestamp NOT NULL,
                           "to" timestamp NOT NULL,
                           PRIMARY KEY ("id")
);


ALTER TABLE "user_roles"
    ADD CONSTRAINT USER_ROLES_USER_ID_FKEY
        FOREIGN KEY (USER_ID)
            REFERENCES "user" (ID);
ALTER TABLE "user_roles"
    ADD CONSTRAINT USER_ROLES_ROLE_ID_FKEY
        FOREIGN KEY (ROLE_ID)
            REFERENCES "role" (ID);
ALTER TABLE "car"
    ADD CONSTRAINT CAR_USER_ID_FKEY
        FOREIGN KEY (USER_ID)
            REFERENCES "user" (ID);
ALTER TABLE "booking"
    ADD CONSTRAINT BOOKING_CAR_ID_FKEY
        FOREIGN KEY (CAR_ID)
            REFERENCES "car" (ID);
ALTER TABLE "booking"
    ADD CONSTRAINT BOOKING_SPOT_ID_FKEY
        FOREIGN KEY (SPOT_ID)
            REFERENCES "spot" (ID);

INSERT INTO "spot" VALUES (1, 'A1');
INSERT INTO "spot" VALUES (2, 'A2');
INSERT INTO "spot" VALUES (3, 'A3');
INSERT INTO "spot" VALUES (4, 'A4');
INSERT INTO "spot" VALUES (5, 'A5');
INSERT INTO "spot" VALUES (6, 'A6');
INSERT INTO "spot" VALUES (7, 'A7');
INSERT INTO "spot" VALUES (8, 'A8');
INSERT INTO "spot" VALUES (9, 'A9');
INSERT INTO "spot" VALUES (10, 'A10');

INSERT INTO "role" VALUES (1, 'ROLE_USER');
INSERT INTO "role" VALUES (2, 'ROLE_ADMIN');
